apiVersion: v1
kind: Service
metadata:
  name: mongo-api-service
  labels:
    app.kubernetes.io/name: fastapi-mongo
    app.kubernetes.io/instance: mongo-api
    app.kubernetes.io/part-of: mongo-loader-app
spec:
  selector:
    app.kubernetes.io/instance: mongo-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP